name: llama_index_app
channels:
  - defaults
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.8
  - pytorch::pytorch=2.2.2
  - pytorch::torchvision=0.17.2
  - pytorch-cuda=12.1
  - pip
  - pip:
    - fire
    - llama-index==0.10.50
    - langchain
    - gradio
    - transformers
    - sentence_transformers
    - InstructorEmbedding
    - spacy
    - llama-index-llms-ollama
    - llama-index-embeddings-ollama
    - sentencepiece
    - git+https://github.com/FlagOpen/FlagEmbedding.git
