name: llama_index_app
channels:
  - defaults
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.10
  - pytorch::pytorch=2.2.2
  - pytorch::torchvision=0.17.2
  - pytorch::pytorch-cuda=12.1
  - conda-forge::huggingface_hub=0.24.1
  - conda-forge::opencv
  - conda-forge::python-dotenv
  - conda-forge::scikit-learn
  - conda-forge::pillow
  - conda-forge::pydantic
  - conda-forge::transformers
  - conda-forge::tabulate
  - conda-forge::ftfy
  - conda-forge::texify
  - conda-forge::rapidfuzz
  - conda-forge::filetype
  - conda-forge::regex
  - conda-forge::pdftext
  - conda-forge::grpcio
  - pip
  - pip:
    - fire
    - git+https://github.com/quoccuongLE/surya.git --no-deps
    - llama-index==0.10.50
    - langchain
    - gradio
    - sentence_transformers
    - InstructorEmbedding
    - spacy
    - llama-index-llms-ollama
    - llama-index-embeddings-ollama
    - llama-index-vector-stores-milvus
    - sentencepiece
    - git+https://github.com/FlagOpen/FlagEmbedding.git
    - ollama
    - flash_attn
    - pymupdf4llm
