name: llama_index_app
channels:
  - defaults
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.10
  - pytorch::pytorch=2.2.2
  - pytorch::torchvision=0.17.2
  - pytorch-cuda=12.1
  - pip
  - pip:
    - fire
    - llama-index==0.10.50
    - langchain
    - gradio
    - transformers
    - sentence_transformers
    - InstructorEmbedding
    - spacy
    - llama-index-llms-ollama
    - llama-index-embeddings-ollama
    - llama-index-vector-stores-milvus
    - sentencepiece
    - git+https://github.com/FlagOpen/FlagEmbedding.git
    - ollama
    - flash_attn
    - pymupdf4llm
    - marker-pdf --no-deps
    - pydantic-settings --no-deps
    - pydantic --no-deps
    - ftfy --no-deps
    - texify --no-deps
    - tabulate --no-deps
    - rapidfuzz --no-deps
    - surya-ocr --no-deps
    - filetype --no-deps
    - regex --no-deps
    - pdftext --no-deps
    - grpcio --no-deps
