index_store: ./data/doc_search/index_store
file_storage: ./data/doc_search/docs
llm:
  model: llama3
  request_timeout: 120.0
embed_model:
  type: ollama
  name: mxbai-embed-large
  max_seq_length: 8192
  request_timeout: 120.0
  instruct_prompt: ""
query_engine:
  type: QA
  similarity_top_k: 12
  hierarchical: false
  chat_token_limit: 12000
  synthesizer:
    topk: 5
    sample_length: 300
parser_config:
  name: llama_parser # simple_parser  llama_parser
  loader_name: pdf_markdown_reader # single_file  llama_parse  pdf_markdown_reader
  loader_config:
    show_progress: true
  index_store_name: vector_store_index
  result_type: markdown
  instruct_prompt: ""
  node_parser_name: markdown_element_node_parser # markdown_node_parser  markdown_element_node_parser
  llm:
    model: llama3
    request_timeout: 120.0
  num_workers: 8